manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # 1. Add the module remote
    - name: infely
      url-base: https://github.com/infely
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # 2. Add the custom battery display module
    - name: nice-view-battery
      remote: infely
      revision: main